config/routes.rb
Rails.application.routes.draw do
  # Rutas para el HomeController
  get "home/index"

  # Rutas para Devise con Controlador Personalizado
  devise_for :users, controllers: {
    registrations: 'users'
  }
  
  # Rutas para Ofertas Laborales
  resources :jobs do
    member do
      post 'apply', to: 'jobs#apply'
    end
  end

  # Rutas para Postulaciones
  resources :applications
  
  # Verificar salud de la aplicación
  get "up" => "rails/health#show", as: :rails_health_check
  
  # Definir la ruta raíz para la página de inicio
  root "home#index"

  # Ruta para perfiles de usuarios manejadas por el controlador personalizado
  resources :users, only: [:show, :edit, :update, :new, :create]
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :user
  belongs_to :job

  validates :user_id, presence: true
  validates :job_id, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :applications

  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Incluye módulos de Devise para autenticación
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Define la relación con los modelos
  has_many :jobs
  has_many :applications

  # Validaciones para los campos adicionales
  validates :photo, presence: true
  validates :relevant_data, presence: true

  # Configuración de roles manual
  ROLE_USER = 0
  ROLE_ADMIN = 1

  def user?
    self.role == ROLE_USER
  end

  def admin?
    self.role == ROLE_ADMIN
  end

  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= ROLE_USER
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo, :relevant_data])
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo, :relevant_data])
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  def index
    @applications = current_user.applications
  end

  def show
  end

  def new
    @application = Application.new
  end

  def create
    @application = current_user.applications.build(application_params)
    if @application.save
      redirect_to @application, notice: 'Application was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @application.update(application_params)
      redirect_to @application, notice: 'Application was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @application.destroy
    redirect_to applications_url, notice: 'Application was successfully destroyed.'
  end

  private

  def set_application
    @application = Application.find(params[:id])
  end

  def application_params
    params.require(:application).permit(:job_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :admin_only, only: [:new, :create, :edit, :update, :destroy]

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    if @job.save
      redirect_to @job, notice: 'Job was successfully created.'
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to @job, notice: 'Job was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_url, notice: 'Job was successfully destroyed.'
  end

  def apply
    @job = Job.find(params[:id])
    current_user.applications.create(job: @job)
    # Aquí puedes añadir la lógica para enviar una notificación a Esteban
    redirect_to @job, notice: 'Your application has been submitted.'
  end

  private

  def admin_only
    redirect_to(root_path) unless current_user.admin?
  end

  def job_params
    params.require(:job).permit(:title, :description)
  end
  
  def apply
    @job = Job.find(params[:id])
    application = current_user.applications.create(job: @job)
    UserMailer.new_application_notification(application).deliver_now
    redirect_to @job, notice: 'Your application has been submitted.'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'Usuario creado exitosamente.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Perfil actualizado exitosamente.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :photo, :relevant_data, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/applications/_application.html.erb
<div id="<%= dom_id application %>">
  <p>
    <strong>User:</strong>
    <%= application.user_id %>
  </p>

  <p>
    <strong>Job:</strong>
    <%= application.job_id %>
  </p>

</div>

app/views/applications/_form.html.erb
<%= form_with(model: application) do |form| %>
  <% if application.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
        <% application.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :job_id, style: "display: block" %>
    <%= form.text_field :job_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<% content_for :title, "Editing application" %>

<h1>Editing application</h1>

<%= render "form", application: @application %>

<br>

<div>
  <%= link_to "Show this application", @application %> |
  <%= link_to "Back to applications", applications_path %>
</div>

app/views/applications/index.html.erb
<h1>Mis Postulaciones</h1>
<ul>
  <% @applications.each do |application| %>
    <li>
      <%= link_to application.job.title, application.job %>
    </li>
  <% end %>
</ul>

app/views/applications/new.html.erb
<% content_for :title, "New application" %>

<h1>New application</h1>

<%= render "form", application: @application %>

<br>

<div>
  <%= link_to "Back to applications", applications_path %>
</div>

app/views/applications/show.html.erb
<h1>Postulación a <%= @application.job.title %></h1>
<p>Usuario: <%= @application.user.email %></p>
<p>Trabajo: <%= link_to @application.job.title, @application.job %></p>

app/views/home/index.html.erb
<h1>Bienvenido a EmpleosInternos</h1>
<%= link_to 'Ingresar', new_user_session_path %>

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>">
  <p>
    <strong>Title:</strong>
    <%= job.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= job.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= job.user_id %>
  </p>

</div>

app/views/jobs/edit.html.erb
<h1>Editar Oferta Laboral</h1>
<%= form_with model: @job, local: true do |form| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>
      <ul>
        <% @job.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit 'Update Job' %>
  </div>
<% end %>

app/views/jobs/index.html.erb
<h1>Ofertas Laborales</h1>
<%= link_to 'Nueva Oferta', new_job_path if current_user&.admin? %>
<ul>
  <% @jobs.each do |job| %>
    <li>
      <%= link_to job.title, job %>
    </li>
  <% end %>
</ul>

app/views/jobs/new.html.erb
<h1>Nueva Oferta Laboral</h1>
<%= form_with model: @job, local: true do |form| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>
      <ul>
        <% @job.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Job' %>
  </div>
<% end %>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>
<p><%= @job.description %></p>
<% if user_signed_in? && !current_user.admin? %>
  <%= button_to 'Postular', apply_job_path(@job), method: :post %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "M6prueba" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <div class="container mt-4">
      <% if notice %>
        <div class="alert alert-info">
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger">
          <%= alert %>
        </div>
      <% end %>

      <%= yield %>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" 
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" 
    integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">
    EmpleosInternos
  </a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link_to 'Inicio', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Ofertas', jobs_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? && current_user.admin? %>
        <li class="nav-item">
          <%= link_to 'Nueva Oferta', new_job_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Gestionar Usuarios', admin_users_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Perfil', user_path(current_user), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Iniciar Sesión', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/_form.html.erb
<%= form_with(model: @user, url: @user.persisted? ? user_path(@user) : users_path, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="field">
    <%= form.label :relevant_data %>
    <%= form.text_area :relevant_data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editar Usuario</h1>
<%= render 'form', user: @user %>
<%= link_to 'Volver', user_path(@user) %>

app/views/users/new.html.erb
<h1>Nuevo Usuario</h1>
<%= render 'form', user: @user %>
<%= link_to 'Volver', users_path %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>
<% if @user.photo.attached? %>
  <%= image_tag @user.photo %>
<% end %>
<p><%= @user.relevant_data %></p>
<%= link_to 'Editar Perfil', edit_user_registration_path %>